### ISSUE TITLE
[psql-app] script gen_whois_route.py doesn´t work

### ISSUE THREAD

**Issue by purifp** [OpenBMP/obmp-docker#14]
hi
I have these errors when the script gen_whois_route.py  is executed:
```
...<omitted by brevity>
===> Checking if we can successfully consume messages
===> Configuring PostgreSQL Shell Profile
===> Enabling RPKI
===> Enabling IRR
Loading IRR data
Starting periodic command scheduler: cron.
rsyslogd: imklog: cannot open kernel log (/proc/kmsg): Operation not permitted.
rsyslogd: activation of module imklog failed [v8.2102.0 try https://www.rsyslog.com/e/2145 ]
Starting enhanced syslogd: rsyslogd.
===> Starting consumer
===> Now running!!!
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Traceback (most recent call last):
  File "/usr/local/openbmp/gen_whois_route.py", line 226, in download_data_file
    ftp = FTP(RR_DB_FTP[source]['site'])
  File "/usr/lib/python3.9/ftplib.py", line 119, in __init__
    self.connect(host)
  File "/usr/lib/python3.9/ftplib.py", line 156, in connect
    self.sock = socket.create_connection((self.host, self.port), self.timeout,
  File "/usr/lib/python3.9/socket.py", line 843, in create_connection
    raise err
  File "/usr/lib/python3.9/socket.py", line 831, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
Traceback (most recent call last):
  File "/usr/local/openbmp/gen_whois_route.py", line 226, in download_data_file
    ftp = FTP(RR_DB_FTP[source]['site'])
  File "/usr/lib/python3.9/ftplib.py", line 119, in __init__
    self.connect(host)
  File "/usr/lib/python3.9/ftplib.py", line 156, in connect
    self.sock = socket.create_connection((self.host, self.port), self.timeout,
  File "/usr/lib/python3.9/socket.py", line 843, in create_connection
    raise err
  File "/usr/lib/python3.9/socket.py", line 831, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out
Traceback (most recent call last):
  File "/usr/local/openbmp/gen_whois_route.py", line 226, in download_data_file
    ftp = FTP(RR_DB_FTP[source]['site'])
  File "/usr/lib/python3.9/ftplib.py", line 119, in __init__
    self.connect(host)
  File "/usr/lib/python3.9/ftplib.py", line 156, in connect
    self.sock = socket.create_connection((self.host, self.port), self.timeout,
  File "/usr/lib/python3.9/socket.py", line 843, in create_connection
    raise err
  File "/usr/lib/python3.9/socket.py", line 831, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out
Traceback (most recent call last):
  File "/usr/local/openbmp/gen_whois_route.py", line 226, in download_data_file
    ftp = FTP(RR_DB_FTP[source]['site'])
  File "/usr/lib/python3.9/ftplib.py", line 119, in __init__
    self.connect(host)
  File "/usr/lib/python3.9/ftplib.py", line 156, in connect
    self.sock = socket.create_connection((self.host, self.port), self.timeout,
  File "/usr/lib/python3.9/socket.py", line 843, in create_connection
    raise err
  File "/usr/lib/python3.9/socket.py", line 831, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
Traceback (most recent call last):
  File "/usr/local/openbmp/gen_whois_route.py", line 226, in download_data_file
    ftp = FTP(RR_DB_FTP[source]['site'])
  File "/usr/lib/python3.9/ftplib.py", line 119, in __init__
    self.connect(host)
  File "/usr/lib/python3.9/ftplib.py", line 156, in connect
    self.sock = socket.create_connection((self.host, self.port), self.timeout,
  File "/usr/lib/python3.9/socket.py", line 843, in create_connection
    raise err
  File "/usr/lib/python3.9/socket.py", line 831, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
Traceback (most recent call last):
  File "/usr/local/openbmp/gen_whois_route.py", line 226, in download_data_file
    ftp = FTP(RR_DB_FTP[source]['site'])
  File "/usr/lib/python3.9/ftplib.py", line 119, in __init__
    self.connect(host)
  File "/usr/lib/python3.9/ftplib.py", line 156, in connect
    self.sock = socket.create_connection((self.host, self.port), self.timeout,
  File "/usr/lib/python3.9/socket.py", line 843, in create_connection
    raise err
  File "/usr/lib/python3.9/socket.py", line 831, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
Traceback (most recent call last):
  File "/usr/local/openbmp/gen_whois_route.py", line 226, in download_data_file
    ftp = FTP(RR_DB_FTP[source]['site'])
  File "/usr/lib/python3.9/ftplib.py", line 119, in __init__
    self.connect(host)
  File "/usr/lib/python3.9/ftplib.py", line 156, in connect
    self.sock = socket.create_connection((self.host, self.port), self.timeout,
  File "/usr/lib/python3.9/socket.py", line 843, in create_connection
    raise err
  File "/usr/lib/python3.9/socket.py", line 831, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out
Traceback (most recent call last):
  File "/usr/local/openbmp/gen_whois_route.py", line 226, in download_data_file
    ftp = FTP(RR_DB_FTP[source]['site'])
  File "/usr/lib/python3.9/ftplib.py", line 119, in __init__
    self.connect(host)
  File "/usr/lib/python3.9/ftplib.py", line 156, in connect
    self.sock = socket.create_connection((self.host, self.port), self.timeout,
  File "/usr/lib/python3.9/socket.py", line 843, in create_connection
    raise err
  File "/usr/lib/python3.9/socket.py", line 831, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
Traceback (most recent call last):
  File "/usr/local/openbmp/gen_whois_route.py", line 226, in download_data_file
    ftp = FTP(RR_DB_FTP[source]['site'])
  File "/usr/lib/python3.9/ftplib.py", line 119, in __init__
    self.connect(host)
  File "/usr/lib/python3.9/ftplib.py", line 156, in connect
    self.sock = socket.create_connection((self.host, self.port), self.timeout,
  File "/usr/lib/python3.9/socket.py", line 843, in create_connection
    raise err
  File "/usr/lib/python3.9/socket.py", line 831, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address 
```
I have connectivity , i have downloaded some of them manually with wget , it seems a ftp problem. Any idea of what is happening ?  
Another thing, some urls are outdated according to https://www.irr.net/docs/list.html.

thanks in advance

**Comment by TimEvens** [comment]
> I have connectivity , i have downloaded some of them manually with wget , it seems a ftp problem. Any idea of what is happening ? Another thing, some urls are outdated according to https://www.irr.net/docs/list.html.

I believe the issue is only with ftp.ripe.net. The others should be working.  Although, radb syncs all the major IRRs, so I'm leaning towards only importing RADb as they have done the work to merge the others into a single DB file that we can consistently import. 

Thoughts?

**Comment by TimEvens** [comment]
Based on your output you are getting ```OSError: [Errno 99] Cannot assign requested address``` errors, which indicates something odd within your container at times.   The script to download the IRR filees from FTP is using basic [ftplib](https://docs.python.org/3/library/ftplib.html), nothing special. What's your base/host OS? 

It's possible at times some of the FTP sites are timing on your instance.   Which one did you see was incorrect?  Regardless, I'm planning to comment out all those and use only RADb considering RADb mirrors the others. This will at least remove some of the problem ones.

**Comment by TimEvens** [comment]
@purifp, are you running the latest and how is it now?

**Comment by TimEvens** [comment]
No activity
