### ISSUE TITLE
Negative number after installation

### ISSUE THREAD

**Issue by kmorales026** [OpenBMP/obmp-docker#5]
Hi, I follow the guide to install and everything is ok, but I did not get graphs on Grafana, my router is configured good to send data to openBMP server.

I check server openBMP server and get Current Offset  negatieve number, why?

root@1bec64379705:/tmp# kafka-tools -b obmp-kafka:29092 print_consumer_lag openbmp.parsed.unicast_prefix obmp-psql-consumer
 Partition   Lag       Latest Offset    Current Offset
-----------  -------  ---------------  ----------------
     7       1               0                -1
     4       1               0                -1
     0       13             12                -1
     6       440,292      440291              -1
     2       1               0                -1
     1       14             13                -1
     3       1               0                -1
     5       1               0                -1

 Total lag: 440,324 messages.
root@1bec64379705:/tmp# 
root@1bec64379705:/tmp#

**Comment by TimEvens** [comment]
a negative 1 indicates that the consumer is likely not connected to Kafka.  What does the ```docker exec  obmp-psql-app cat /var/log/obmp-psql.log``` show in terms of errors/warnings?

**Comment by TimEvens** [comment]
@kmorales026 , let's reopen if you still have an issue with version 2.1.1.

**Comment by kmorales026** [comment]
I received this error:

root@ubuntu:/var/openbmp/config# docker exec obmp-psql-app cat /var/log/obmp-psql.log
2022-06-20 19:16:35 137 [main] INFO  org.openbmp.ConsumerApp - Loading custom configuration file
2022-06-20 19:16:35 137 [main] INFO  org.openbmp.PSQLHandler - Connecting to Postgres
2022-06-20 19:16:37 137 [main] WARN  org.openbmp.PSQLHandler - Writer thread failed to connect to psql
org.postgresql.util.PSQLException: Connection to obmp-psql:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:301) ~[obmp-psql-consumer.jar:?]
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51) ~[obmp-psql-consumer.jar:?]
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:225) ~[obmp-psql-consumer.jar:?]
        at org.postgresql.Driver.makeConnection(Driver.java:466) ~[obmp-psql-consumer.jar:?]
        at org.postgresql.Driver.connect(Driver.java:265) ~[obmp-psql-consumer.jar:?]
        at java.sql.DriverManager.getConnection(DriverManager.java:681) ~[java.sql:?]
        at java.sql.DriverManager.getConnection(DriverManager.java:190) ~[java.sql:?]
        at org.openbmp.PSQLHandler.connect(PSQLHandler.java:94) [obmp-psql-consumer.jar:?]
        at org.openbmp.ConsumerApp.main(ConsumerApp.java:95) [obmp-psql-consumer.jar:?]
Caused by: java.net.ConnectException: Connection refused
        at sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
        at sun.nio.ch.Net.pollConnectNow(Net.java:672) ~[?:?]
        at sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542) ~[?:?]
        at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597) ~[?:?]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
        at java.net.Socket.connect(Socket.java:633) ~[?:?]
        at org.postgresql.core.PGStream.createSocket(PGStream.java:238) ~[obmp-psql-consumer.jar:?]
        at org.postgresql.core.PGStream.<init>(PGStream.java:98) ~[obmp-psql-consumer.jar:?]
        at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:100) ~[obmp-psql-consumer.jar:?]
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:215) ~[obmp-psql-consumer.jar:?]
        ... 8 more
2022-06-20 19:16:37 137 [main] ERROR org.openbmp.ConsumerApp - Failed to connect to db.  Check configuration and try again.
root@ubuntu:/var/openbmp/config#

**Comment by TimEvens** [comment]
@kmorales026 , Did you do an upgrade or fresh install?  The issue you describe above is consistent with the ```obmp-psql``` container not running.  Can you provide the ```docker logs obmp-psql``` output?

**Comment by kmorales026** [comment]
Hi @TimEvens !, thanks!, 

I fixed some issue about the user who run docker container, but now the dashboard show many error about queries PostgreSQL.  I just configured my Router to use BMP Server, but  I dont know anything about SQL, 

![image](https://user-images.githubusercontent.com/36080974/174896010-e2dfa28f-3f8a-48fe-9584-059cc6220159.png)
